version: '3.1'
networks:
  main:
services:
  mongodb:
    image: mvertes/alpine-mongo:latest
    volumes:
      - "./devdata:/devdata:delegated"
      - "./.dev/mongo/data/db:/data/db:delegated"
      - "./.dev/log/mongo:/var/log/mongo:delegated"
    networks:
      main:
        aliases:
          - mongodb
    ports:
      - "27017:27017"
    expose:
      - "27017"
  solr:
    image: solr:latest
    expose:
      - "8983"
    ports:
      - "8983:8983"
    networks:
      main:
       aliases:
         - solr
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - redbox
